### ISSUE TITLE
Issue building Deformable-Convolution-V2-PyTorch

### ISSUE THREAD

**Issue by elias-ramzi** [jdonnelly36/Deformable-ProtoPNet#2]
Hi,

Thank you for this repository!

Could you precise what are the versions of torch and torchvision that should be used to build the repo ?

Thanks,
Elias

**Comment by jdonnelly36** [comment]
Hi Elias,

I've updated the readme file with version info for each package! Do let me know if you run into any more issues.

Best,
Jon

**Comment by elias-ramzi** [comment]
Hi,

Thank you for your response.
Could also update the README with your python, and cuda versions ?

I am still having issues with the installation :\

I have the following error:
```
fatal error: cuda_runtime_api.h: No such file or directory
```

Which leads to a final error:
```
RuntimeError: Error compiling objects for extension
```

Thanks,
Elias

**Comment by jdonnelly36** [comment]
Hi Elias,

I've added the python version (3.8.5) to the readme, and torch was installed with cuda version 11.1 (I didn't add this to the readme because it's a bit more dependent on your server setup than the other stuff). 

Is this issue happening when you try to build the deformable convolution stuff? Are those errors coming from running make.sh?

**Comment by elias-ramzi** [comment]
I had issues on the servers of my lab.

I was able to build the deformable convolution part on an other GPU cluster.

I will come back to you if I have other issues.

Thanks again :)
Elias
